fc20-service-apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

fc20-service-php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

fc20-service-mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

fc20-service-postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

fc20-service-mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

fc20-service-ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

fc20-service-memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server
