pma:
  build: Applications/phpmyadmin/
  container_name: "startx-app-phpmyadmin"
  ports:
    - "82:80"
    - "445:443"

rockmongo:
  build: Applications/rockmongo/
  container_name: "startx-app-rockmongo"
  ports:
    - "83:80"
    - "446:443"