fc22_apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

fc22_php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

fc22_nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

fc22_mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

fc22_postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

fc22_mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

fc22_ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

fc22_memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server
