centos6-service-apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

centos6-service-php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

centos6-service-nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

centos6-service-mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

centos6-service-postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

centos6-service-mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

centos6-service-ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

centos6-service-memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server
    
centos6-service-couchbase:
  extends:
    file: Services/couchbase/docker-compose.yml
    service: server
