fedora23:
  extends:
    file: OS/docker-compose.yml
    service: fedora23

fc23_sv_apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

fc23_sv_php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

fc23_sv_nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

fc23_sv_mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

fc23_sv_postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

fc23_sv_mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

fc23_sv_ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

fc23_sv_memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server

fc23_app_pma:
  build: Applications/phpmyadmin/
  container_name: "application-phpmyadmin"

#fc23_app_rockmongo:
#  build: Applications/rockmongo/
#  container_name: "application-rockmongo"