centos6:
  extends:
    file: OS/docker-compose.yml
    service: centos6

centos6_apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

centos6_php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

centos6_nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

centos6_mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

centos6_postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

centos6_mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

centos6_ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

centos6_memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server

#pma:
#  build: Applications/phpmyadmin/
#  container_name: "startx-app-phpmyadmin"
#
#rockmongo:
#  build: Applications/rockmongo/
#  container_name: "startx-app-rockmongo"