fedora20:
  extends:
    file: OS/docker-compose.yml
    service: fedora20

fc20_apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

fc20_php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

#fc20_nodejs:
#  extends:
#    file: Services/nodejs/docker-compose.yml
#    service: server

fc20_mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

fc20_postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

fc20_mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

fc20_ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

fc20_memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server

#pma:
#  build: Applications/phpmyadmin/
#  container_name: "startx-app-phpmyadmin"
#
#rockmongo:
#  build: Applications/rockmongo/
#  container_name: "startx-app-rockmongo"