fc23-data:
  image: startx/fedora
  container_name: "fc23-data"
  environment:
    CONTAINER_TYPE: "os"
    CONTAINER_SERVICE: "fedora"
    CONTAINER_INSTANCE: "fc23-data"

fc23-service-apache:
  image: startx/sv-apache
  container_name: "fc23-service-apache"
  ports:
    - "81:80"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "apache"
    CONTAINER_INSTANCE: "fc23-service-apache"
  volumes_from:
    - fc23-data

fc23-service-php:
  image: startx/sv-php
  container_name: "fc23-service-php"
  ports:
    - "82:80"
  links:
    - fc23-service-mariadb:mariadb
    - fc23-service-postgres:postgres
    - fc23-service-mongo:mongo
    - fc23-service-memcache:memcache
    - fc23-service-ooconv:ooconv
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "php"
    CONTAINER_INSTANCE: "fc23-service-php"
  volumes_from:
    - fc23-data

fc23-service-nodejs:
  image: startx/sv-nodejs
  container_name: "fc23-service-nodejs"
  ports:
    - "83:8000"
  links:
    - fc23-service-mariadb:mariadb
    - fc23-service-postgres:postgres
    - fc23-service-mongo:mongo
    - fc23-service-memcache:memcache
    - fc23-service-ooconv:ooconv
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "nodejs"
    CONTAINER_INSTANCE: "fc23-service-nodejs"
  volumes_from:
    - fc23-data

fc23-service-mariadb:
  image: startx/sv-mariadb
  container_name: "fc23-service-mariadb"
  expose:
    - "3306"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mariadb"
    CONTAINER_INSTANCE: "fc23-service-mariadb"
    MYSQL_USER: "user-test"
    MYSQL_PASSWORD: "pwd-test"
    MYSQL_DATABASE: "db_test"
  volumes_from:
    - fc23-data

fc23-service-postgres:
  image: startx/sv-postgres:latest
  container_name: "fc23-service-postgres"
  expose:
    - "5432"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "postgres"
    CONTAINER_INSTANCE: "fc23-service-postgres"
    POSTGRESQL_USER: "user-test"
    POSTGRESQL_PASSWORD: "pwd-test"
    POSTGRESQL_DATABASE: "db_test"
  volumes_from:
    - fc23-data

fc23-service-mongo:
  image: startx/sv-mongo
  container_name: "fc23-service-mongo"
  expose:
    - "27017"
    - "28017"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mongo"
    CONTAINER_INSTANCE: "fc23-service-mongo"
  volumes_from:
    - fc23-data

fc23-service-ooconv:
  image: startx/sv-ooconv
  container_name: "fc23-service-ooconv"
  expose:
    - "2002"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "ooconv"
    CONTAINER_INSTANCE: "fc23-service-ooconv"
  volumes_from:
    - fc23-data

fc23-service-memcache:
  image: startx/sv-memcache
  container_name: "fc23-service-memcache"
  expose:
    - "11211"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
    CONTAINER_INSTANCE: "fc23-service-memcache"
  volumes_from:
    - fc23-data

#fedora_app_pma:
#  image: startx/sv-phpmyadmin
#  container_name: "application-phpmyadmin"
#  ports:
#    - "84:80"
#  links:
#    - fc23-service-mariadb:mariadb
#  environment:
#    CONTAINER_TYPE: "application"
#    CONTAINER_SERVICE: "phpmyadmin"
#    CONTAINER_INSTANCE: "application-phpmyadmin"
#  volumes_from:
#    - fc23-data

#fedora_app_rockmongo:
#  build: Applications/rockmongo/
#  container_name: "application-rockmongo"