os:
  extends:
    file: OS/docker-compose.yml
    service: fedora
    
apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server
    
php:
  extends:
    file: Services/php/docker-compose.yml
    service: server
    
mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server
    
memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server

#mongo:
#  extends:
#    file: Services/mongo/docker-compose.yml
#    service: server

#nodejs:
#  build: Services/nodejs/
#  container_name: "startx-sv-nodejs"
#  command: node /app/app.js

#ooconv:
#  build: Services/ooconv/
#  container_name: "startx-sv-ooconv"

#postgres:
#  build: Services/postgres/
#  container_name: "startx-sv-postgres"

#pma:
#  build: Applications/phpmyadmin/
#  container_name: "startx-app-phpmyadmin"
#
#rockmongo:
#  build: Applications/rockmongo/
#  container_name: "startx-app-rockmongo"