os:
  extends:
    file: OS/docker-compose.yml
    service: fedora

apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server

mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

#pma:
#  build: Applications/phpmyadmin/
#  container_name: "startx-app-phpmyadmin"
#
#rockmongo:
#  build: Applications/rockmongo/
#  container_name: "startx-app-rockmongo"