fedora_data:
  image: startx/fedora
  container_name: "fedora_data"
  environment:
    CONTAINER_TYPE: "os"
    CONTAINER_SERVICE: "fedora"
    CONTAINER_INSTANCE: "fedora_data"

fedora_sv_apache:
  image: startx/sv-apache
  container_name: "fedora_sv_apache"
  ports:
    - "81:80"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "apache"
    CONTAINER_INSTANCE: "fedora_sv_apache"
  volumes_from:
    - fedora_data

fedora_sv_php:
  image: startx/sv-php
  container_name: "fedora_sv_php"
  ports:
    - "82:80"
  links:
    - fedora_sv_mariadb:mariadb
    - fedora_sv_postgres:postgres
    - fedora_sv_mongo:mongo
    - fedora_sv_memcache:memcache
    - fedora_sv_ooconv:ooconv
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "php"
    CONTAINER_INSTANCE: "fedora_sv_php"
  volumes_from:
    - fedora_data

fedora_sv_nodejs:
  image: startx/sv-nodejs
  container_name: "fedora_sv_nodejs"
  ports:
    - "83:8000"
  links:
    - fedora_sv_mariadb:mariadb
    - fedora_sv_postgres:postgres
    - fedora_sv_mongo:mongo
    - fedora_sv_memcache:memcache
    - fedora_sv_ooconv:ooconv
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "nodejs"
    CONTAINER_INSTANCE: "fedora_sv_nodejs"
  volumes_from:
    - fedora_data

fedora_sv_mariadb:
  image: startx/sv-mariadb
  container_name: "fedora_sv_mariadb"
  expose:
    - "3306"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mariadb"
    CONTAINER_INSTANCE: "fedora_sv_mariadb"
    MYSQL_USER: "user-test"
    MYSQL_PASSWORD: "pwd-test"
    MYSQL_DATABASE: "db_test"
  volumes_from:
    - fedora_data

fedora_sv_postgres:
  image: startx/sv-postgres:latest
  container_name: "fedora_sv_postgres"
  expose:
    - "5432"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "postgres"
    CONTAINER_INSTANCE: "fedora_sv_postgres"
    POSTGRESQL_USER: "user-test"
    POSTGRESQL_PASSWORD: "pwd-test"
    POSTGRESQL_DATABASE: "db_test"
  volumes_from:
    - fedora_data

fedora_sv_mongo:
  image: startx/sv-mongo
  container_name: "fedora_sv_mongo"
  expose:
    - "27017"
    - "28017"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mongo"
    CONTAINER_INSTANCE: "fedora_sv_mongo"
  volumes_from:
    - fedora_data

fedora_sv_ooconv:
  image: startx/sv-ooconv
  container_name: "fedora_sv_ooconv"
  expose:
    - "2002"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "ooconv"
    CONTAINER_INSTANCE: "fedora_sv_ooconv"
  volumes_from:
    - fedora_data

fedora_sv_memcache:
  image: startx/sv-memcache
  container_name: "fedora_sv_memcache"
  expose:
    - "11211"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
    CONTAINER_INSTANCE: "fedora_sv_memcache"
  volumes_from:
    - fedora_data

#fedora_app_pma:
#  image: startx/sv-phpmyadmin
#  container_name: "application-phpmyadmin"
#  ports:
#    - "84:80"
#  links:
#    - fedora_sv_mariadb:mariadb
#  environment:
#    CONTAINER_TYPE: "application"
#    CONTAINER_SERVICE: "phpmyadmin"
#    CONTAINER_INSTANCE: "application-phpmyadmin"
#  volumes_from:
#    - fedora_data

#fedora_app_rockmongo:
#  build: Applications/rockmongo/
#  container_name: "application-rockmongo"