server:
  build: ./
  container_name: "mongo-fc23"
  mem_limit: 2g
  memswap_limit: 2g
  cpu_shares: 10
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mongo"
    CONTAINER_INSTANCE: "sx-mongo"
  volumes:
    - "/tmp/container-fc23/logs/mongodb:/data/logs/mongodb"
    - "/tmp/container-fc23/mongodb:/data/mongodb"