server:
  build: ./
  container_name: "mongo-fc21"
  mem_limit: 2g
  memswap_limit: 2g
  cpu_shares: 10
  restart: "on-failure:2"
  ports:
    - "27017:27017"
    - "28017:28017"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mongo"
    CONTAINER_INSTANCE: "sx-mongo"
  volumes:
    - "/tmp/container-fc21/logs/mongodb:/data/logs/mongodb"
    - "/tmp/container-fc21/mongodb:/data/mongodb"
