server:
  build: ./
#  image: sx-mongo
  container_name: "sx-mongo"
  mem_limit: 2g
  memswap_limit: 2g
  cpu_shares: 10
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mongo"
    CONTAINER_INSTANCE: "sx-mongo"
  volumes:
    - "/tmp/container/logs/mongodb:/data/logs/mongodb"
    - "/tmp/container/mongodb:/data/mongodb"