server:
  build: ./
  container_name: "memcache-fc23"
  mem_limit: 2g
  memswap_limit: 3g
  cpu_shares: 2
  restart: "on-failure:2"
  ports:
    - "11211:11211"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
    CONTAINER_INSTANCE: "service-memcache"
  volumes:
    - "/tmp/container-fc23/logs/memcache:/data/logs/memcache"