server:
  build: ./
  container_name: "memcache-fc22"
  mem_limit: 1.5g
  memswap_limit: 500m
  cpu_shares: 2
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
    CONTAINER_INSTANCE: "service-memcache"
  volumes:
    - "/tmp/container/logs/memcache:/data/logs/memcache"
    - "/tmp/container/memcache:/data/memcache"