server:
  build: ./
#  image: sv-memcache
  container_name: "memcache-server"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 2
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "memcache"
    CONTAINER_INSTANCE: "service-memcache"
  volumes:
    - "/tmp/container/logs/memcache:/data/logs/memcache"
    - "/tmp/container/memcache:/data/memcache"