server:
  build: ./
#  image: sx-fedora
  container_name: "sx-fedora"
  mem_limit: 1g
  memswap_limit: 2g
  cpu_shares: 2
  restart: "on-failure:2"
  environment:
    CONTAINER_SERVICE: "os"
    CONTAINER_TYPE: "fedora"
    CONTAINER_INSTANCE: "sx-fedora"