server:
  build: ./
  container_name: "postgres-fc20"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 8
  restart: "on-failure:2"
  ports:
    - "9241:5432"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "postgresql"
    CONTAINER_INSTANCE: "sx-postgresql"
    POSTGRESQL_ROOT_PASSWORD: "secretdemerde"
    POSTGRESQL_USER: "user-test"
    POSTGRESQL_PASSWORD: "pwd-test"
    POSTGRESQL_DATABASE: "db_test"
  volumes:
    - "/tmp/container-fc20/logs/postgresql:/data/logs/postgresql"
    - "/tmp/container-fc20/postgresql:/data/postgresql"
