server:
  build: ./
#  image: sx-postgresql
  container_name: "sx-postgresql"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 8
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "postgresql"
    CONTAINER_INSTANCE: "sx-postgresql"
    POSTGRESQL_ROOT_PASSWORD: "secretdemerde"
    POSTGRESQL_USER: "user-test"
    POSTGRESQL_PASSWORD: "pwd-test"
    POSTGRESQL_DATABASE: "db_test"
  volumes:
    - "/tmp/container/logs/postgresql:/data/logs/postgresql"
    - "/tmp/container/postgresql:/data/postgresql"