server:
  build: ./
  container_name: "ooconv-fc23"
  mem_limit: 2g
  memswap_limit: 2g
  cpu_shares: 8
  restart: "on-failure:2"
  ports:
    - "9261:2002"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "ooconv"
    CONTAINER_INSTANCE: "service-ooconv"
  volumes:
    - "/tmp/container-fc23/logs/ooconv:/data/logs/ooconv"