server:
  build: ./
#  image: sv-ooconv
  container_name: "ooconv-fc23"
  mem_limit: 2g
  memswap_limit: 2g
  cpu_shares: 8
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "ooconv"
    CONTAINER_INSTANCE: "service-ooconv"
  volumes:
    - "/tmp/container/logs/ooconv:/data/logs/ooconv"