apache:
  build: ./
#  image: sx-apache
  container_name: "sx-apache"
  mem_limit: 1g
  memswap_limit: 2g
  cpu_shares: 2
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "apache"
    CONTAINER_INSTANCE: "sx-apache"
  volumes:
    - "/tmp/container/logs:/data/logs"
    - "/tmp/container/www:/data/www"