httpd:
  build: ./
#  image: sx-httpd
  container_name: "sx-httpd"
  mem_limit: 1g
  memswap_limit: 2g
  cpu_shares: 2
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "httpd"
    CONTAINER_INSTANCE: "sx-httpd"
    SERVER_NAME: "localhost"
    DOC_ROOT: "/data/httpd"
  volumes:
    - "/tmp/container/logs/httpd:/data/logs/httpd"
    - "/tmp/container/httpd:/data/httpd"