server:
  build: ./
  container_name: "php-centos6"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 5
  restart: "on-failure:2"
  ports:
    - "9213:80"
    - "9214:443"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "php"
    CONTAINER_INSTANCE: "service-apache_php"
    SERVER_NAME: "localhost"
    DOC_ROOT: "/data/apache_php"
  volumes:
    - "/tmp/container-centos6/logs/apache_php:/data/logs/apache_php"
    - "/tmp/container-centos6/apache_php:/data/apache_php"