server:
  build: ./
  container_name: "mariadb-fc21"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 8
  restart: "on-failure:2"
  ports:
    - "3306:3306"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mariadb"
    CONTAINER_INSTANCE: "sx-mariadb"
    MYSQL_ROOT_PASSWORD: "secretdemerde"
    MYSQL_USER: "user-test"
    MYSQL_PASSWORD: "pwd-test"
    MYSQL_DATABASE: "db_test"
  volumes:
    - "/tmp/container-fc21/logs/mariadb:/data/logs/mariadb"
    - "/tmp/container-fc21/mariadb:/data/mariadb"
