mariadb:
  build: ./
#  image: sx-mariadb
  container_name: "sx-mariadb"
  mem_limit: 1g
  memswap_limit: 2g
  cpu_shares: 2
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "mariadb"
    CONTAINER_INSTANCE: "sx-mariadb"
  volumes:
    - "/tmp/container/logs:/data/logs"
    - "/tmp/container/mariadb:/data/mariadb"