server:
  build: ./
  container_name: "fc23-service-nodejs"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 5
  restart: "on-failure:2"
  ports:
    - "9221:8000"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "nodejs"
    CONTAINER_INSTANCE: "fc23-service-nodejs"
  volumes:
    - "/tmp/container-fc23/logs/nodejs:/data/logs/nodejs"
    - "/tmp/container-fc23/nodejs:/data/nodejs"